[package]
name = "ised"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
itertools = "0.14.0"
regex = "1.11.1"
tui = "0.19"
walkdir = "2.4"

[dev-dependencies]
tempfile = "3"
assert_fs = "1"
